export const KEYS = {
  LOGIN: "admin-login",
  SEND_PASSWORD_EMAIL: "forgot-password-request",
  VERIFY_OTP: "verify-otp",
  RESET_PASSWORD: "reset-password",
  ChANGE_PASSWORD: "change-password",
  WORKSHOP: {
    ALL: "workshop",
    ADD: "add-workshop",
    EDIT: "edit-workshop",
    DELETE: "delete-workshop",
    MESSAGE: "send-message-workshop",
  },
  UPLOAD: {
    ADD: "upload",
    DELETE: "upload",
  },
  COURSES: {
    ALL: "courses",
    ADD: "add-courses",
    EDIT: "edit-courses",
    DELETE: "delete-courses",
    MESSAGE: "send-message-courses",
  },
  BANNER: {
    ALL: "banner",
    ADD: "add-banner",
    EDIT: "edit-banner",
    DELETE: "delete-banner",
  },
  ACHIEVEMENTS: {
    ALL: "achievements",
    ADD: "add-achievements",
    EDIT: "edit-achievements",
    DELETE: "delete-achievements",
  },
  TESTOMONIALS: {
    ALL: "testomonials",
    ADD: "add-testomonials",
    EDIT: "edit-testomonials",
    DELETE: "delete-testomonials",
  },
  FAQ: {
    ALL: "faq",
    ADD: "add-faq",
    EDIT: "edit-faq",
    DELETE: "delete-faq",
  },
  WEB_SETTING: {
    ALL: "web-setting",
    ADD_EDIT: "add-edit-web-setting",
  },
  ADMIN_SETTING: {
    ALL: "admin-setting",
    ADD_EDIT: "update-profile",
  },
  COURSES_REGISTER: {
    ALL: "course-register",
    EDIT: "edit-course-register",
    DELETE: "delete-course-register",
    MESSAGE: "send-message-course-register",
  },
  WORKSHOP_REGISTER: {
    ALL: "workshop-register",
    EDIT: "edit-workshop-register",
    DELETE: "delete-workshop-register",
    MESSAGE: "send-message-workshop-register",
  },
  ABOUT: {
    ALL: "about",
    ADD_EDIT: "add-edit-about",
  },
  LANGUAGE: {
    ALL: "language",
    ADD: "add-language",
    EDIT: "edit-language",
    DELETE: "delete-language",
  },
  USER_REGISTRATION: {
    ALL: "user-registration",
    MESSAGE: "send-message-user-registration",
  },
  NEWS_LETTER: {
    ALL: "news-letter",
    ADD: "add-news-letter",
    EDIT: "edit-news-letter",
    DELETE: "delete-news-letter",
    MESSAGE: "send-message-news-letter",
  },
  BLOG: {
    ALL: "blog",
    ADD: "add-blog",
    EDIT: "edit-blog",
    DELETE: "delete-blog",
  },
  CONTACT_US: {
    ALL: "contact-us",
    ADD: "add-contact-us",
    EDIT: "edit-contact-us",
    DELETE: "delete-contact-us",
  },
  DASHBOARD: {
    ALL: "dashboard",
  },
} as const;
